import Head from "next/head";
import Image from "next/image";

// import Component Start

import Header from "./../Components/home/Header/Header";
import PartOne from "./../Components/home/PartOne/PartOne";
import BestTour from "./../Components/home/BestTour/BestTour";
import TourismMagazine from "../Components/home/TourismMagazine";
import ShahrZardDes from "../Components/home/shahrZardDes";
import FrequentlyAsked from "../Components/home/frequentlyAsked";
import Footer from "../Components/home/Footer";
import { GetServerSideProps } from "next";
import { itemsFooter } from "../utils/data";
import Slider from "../Components/home/Slider/index";

// import Component End
interface Props {
  cities: {}[];
}
export default function Home({ cities }: Props) {
  return (
    <div>
      <Head>
        <title>Shahrzadbaal</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <PartOne cities={cities}/>
        <div style={{ width: "80%", margin: "0 auto" }}>
          <BestTour />
        </div>
        <Slider />
        <div style={{ width: "80%", margin: "0 auto" }}>
          <TourismMagazine />
          <ShahrZardDes />
          <FrequentlyAsked />
        </div>
      </main>
      <Footer />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps =
  async (ctx) => {
 
    const data = {
      pageNumber: null,
      pageSize: null,
      name: "",
      fk_OstanId: null,
      fk_CountryId: null,
      isPriority: true,
    };
    const getCitys = await fetch(
      // `${process.env.HOST}/City/getCitys`,
      `http://62.3.41.67:8090/api/City/getCitys`,
      {
        method: "POST",
        headers: {
          "Content-type": "application/json",
        },
        body: JSON.stringify(data),
      }
    );
    const cities = await getCitys.json();

    return {
      props: {
        cities: cities.cityList,
      },
    };
  };
