import Head from "next/head";
import Image from "next/image";

// import Component Start

import Header from "./../Components/home/Header/Header";
import PartOne from "./../Components/home/PartOne/PartOne";
import BestTour from "./../Components/home/BestTour/BestTour";
import TourismMagazine from "../Components/home/TourismMagazine";
import ShahrZardDes from "../Components/home/shahrZardDes";
import FrequentlyAsked from "../Components/home/frequentlyAsked";
import Footer from "../Components/home/Footer";
import { GetServerSideProps } from "next";
import { itemsFooter } from "../utils/data";
import Slider from "../Components/home/Slider/index";

// import Component End

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shahrzadbaal</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <PartOne />
        <div style={{ width: "80%", margin: "0 auto" }}>
          <BestTour />
        </div>
        <Slider />
        <div style={{ width: "80%", margin: "0 auto" }}>
          <TourismMagazine />
          <ShahrZardDes />
          <FrequentlyAsked />
        </div>
      </main>
      <Footer />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps =
  async (ctx) => {
    const token = ctx.req.cookies["token"];
    if (!token) {
      return {
        redirect: {
          destination: "/login",
          permanent: false,
        },
      };
    }
    return {
      props: {},
    };
  };
